name: Test
description: Run tests
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Run Quality Check
      run: bin/rubocop

    - name: Setup Database
      run: bin/rails db:setup
      env:
        RAILS_ENV: test
        DATABASE_HOST: localhost
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres

    - name: Run Tests
      run: bin/rspec
      env:
        RAILS_ENV: test
        DATABASE_HOST: localhost
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
